### ISSUE TITLE
Copy the Hello World component example as a starter boilerplate

### ISSUE THREAD

**Issue by rcrowe-google** [rcrowe-google/schemacomponent#2]
For a place to start

**Comment by deutranium** [comment]
Apart from the boilerplate, this issue also involves ensuring the creation of the following:

- **README.md:** Includes the general introduction about the project along with instructions to setup/run the component etc.
- **CONTRIBUTING.md:** With contributing guidelines including git best practices etc.
- **PROPOSAL.md:** The component proposal
